configfile: "./cellprofiler_ap.json"


# Load rules
include: "rules/common.smk"
include: "rules/processing.smk"

# Define wildcards
name = config["name"]
scenario = config["workflow"]
categories = config["categories"]
features = config["features"]

#rule create_dirs:
    #output:
        #directory(f"outputs/{config['features']}/{config['name']}/profiles/")
    #shell:
        #"mkdir -p {output}"


rule all:
    input:
        #"outputs/cellprofiler/mad_featselect_ap/curves/plots/cp_plots.pdf",
        #"outputs/cellprofiler/mad_featselect_ap/classifier_results/axiom_continuous_predictions.parquet",
        #"outputs/cellprofiler/mad_featselect_ap/classifier_results/toxcast_cellbased_binary_predictions.parquet",
        #"outputs/cellprofiler/mad_featselect_ap/classifier_results/toxcast_cellfree_binary_predictions.parquet",
        #"outputs/cellprofiler/mad_featselect_ap/classifier_results/axiom_binary_predictions.parquet",
        #"outputs/cellprofiler/mad_featselect_ap/classifier_results/toxcast_cytotox_binary_predictions.parquet",
        "outputs/profiles/mad_featselect.parquet"
